/** Checklist-tab strings in both languages the field form offers. */
export const CHECKLIST_LABELS = {
  en: {
    title: 'Daily Inspection Checklist',
    asset: 'Asset Number',
    position: 'Position',
    pressure: 'Pressure (PSI)',
    condition: 'Condition',
    tread: 'Tread (mm)',
    notes: 'Notes',
    good: 'Good',
    wear: 'Wear',
    damage: 'Damage',
    puncture: 'Puncture',
    save: 'Save Checklist',
    export: 'Export PDF',
    inspector: 'Inspector',
    site: 'Site',
    no_asset: 'Enter asset number to load vehicle',
  },
  ar: {
    title: 'قائمة الفحص اليومي',
    asset: 'رقم الأصل',
    position: 'الموضع',
    pressure: 'الضغط (PSI)',
    condition: 'الحالة',
    tread: 'عمق المداس (مم)',
    notes: 'ملاحظات',
    good: 'جيد',
    wear: 'تآكل',
    damage: 'تلف',
    puncture: 'ثقب',
    save: 'حفظ القائمة',
    export: 'تصدير PDF',
    inspector: 'المفتش',
    site: 'الموقع',
    no_asset: 'أدخل رقم الأصل لتحميل المركبة',
  },
}
