/**
 * Service-layer barrel. Import domain services as namespaces:
 *   import { assets, tyres } from '../lib/api'
 *   const rows = await assets.listAssets({ country })
 *
 * More domain modules (inspections, workOrders, stock, accidents, uploads,
 * reports, organisations, users) are added here as each is migrated.
 */
export * as assets from './assets'
export * as tyres from './tyres'
export * as stock from './stock'
export * as workOrders from './workOrders'
export * as inspections from './inspections'
export * as accidents from './accidents'
export * as gatePasses from './gatePasses'
export * as correctiveActions from './correctiveActions'
export * as rca from './rca'
export * as warranty from './warranty'
export * as recalls from './recalls'
export * as alertThresholds from './alertThresholds'
export * as rotations from './rotations'
export * as kpiTargets from './kpiTargets'
export * as purchaseOrders from './purchaseOrders'
export * as customData from './customData'
export * as knowledgeDocuments from './knowledgeDocuments'
export * as users from './users'
export * as budgets from './budgets'
export * as dashboard from './dashboard'
export * as dataCleaning from './dataCleaning'
export * as uploads from './uploads'
export * as settings from './settings'
export * as tyreSpecs from './tyreSpecs'
export * as procurement from './procurement'
export * as tyreRecords from './tyreRecords'
export * as continuousImprovement from './continuousImprovement'
export * as vehicleHistory from './vehicleHistory'
export * as supplierManagement from './supplierManagementApi'
export * as assetManagement from './assetManagement'
export * as gatePassPage from './gatePassPage'
export * as engineeringKpi from './engineeringKpi'
export * as inspectionIntelligence from './inspectionIntelligence'
export * as tyreScrap from './tyreScrap'
export * as tyreExchange from './tyreExchange'
export * as tyreAgeCompliance from './tyreAgeCompliance'
export * as tyrePassport from './tyrePassport'
export * as fitmentValidation from './fitmentValidation'
export * as technicianScorecard from './technicianScorecard'
export * as tyrePool from './tyrePool'
export * as opsIntelligence from './opsIntelligence'
export * as fleetRisk from './fleetRisk'
export * as rotationOptimizer from './rotationOptimizer'
export * as carbon from './carbon'
export * as tpms from './tpms'
export * as contracts from './contracts'
export * as rfid from './rfid'
export * as geofences from './geofences'
export * as insuranceClaims from './insuranceClaims'
export * as fuelCards from './fuelCards'
export * as certifications from './certifications'
export * as incidents from './incidents'
export * as journeys from './journeys'
export * as policies from './policies'
export * as digitalTwin from './digitalTwin'
export { ServiceError, unwrap, applyCountry } from './_client'
