// Module copy is colocated so the governed workspace ships atomically in both languages.
export const approvalPolicyCopy = {
  en: {
    title: 'Approval Matrix', subtitle: 'Governed policies shared by web and mobile. Higher priority wins, then the number of matching conditions. Equal-ranked overlaps block publication.',
    refresh: 'Refresh', retry: 'Retry', loading: 'Loading…', unavailable: 'Approval configuration is unavailable. Check access or backend readiness, then retry.',
    partial: 'People, sites or roles could not be verified. Configuration actions are disabled until all reference data loads.',
    policies: 'Policies', search: 'Search policies', all: 'All', draft_saved: 'Draft saved', draft: 'Draft', published: 'Published', retired: 'Retired',
    empty: 'No policies match this scope. Use simulation to check module mode. Retiring the last policy does not disable enforcement.',
    inspection: 'Tyre inspection', checklist: 'Checklist', work_order: 'Work order execution', tyre_change: 'Tyre operation execution', unsupported: 'Accident approval remains under its existing module rules.',
    edit: 'Edit draft', clone: 'Clone as draft', history: 'History', publish: 'Publish', retire: 'Retire', close: 'Close',
    new: 'New policy', editor: 'Policy draft', name: 'Policy name', type: 'Module', country: 'Country', anyCountry: 'Any country',
    site: 'Site', anySite: 'Any site', countryFirst: 'Choose a country before selecting a site.', role: 'Submitting role', person: 'Submitting person',
    anyRole: 'Any role', anyPerson: 'Any person', priority: 'Priority', priorityHint: 'Higher numbers take precedence. Ambiguous overlaps are rejected by the server.',
    stages: 'Sequential review stages', stage: 'Stage', stageName: 'Stage name', reviewerRole: 'Reviewer role', reviewerPerson: 'Named reviewer',
    eligibilityHint: 'A reviewer must have current module permission and matching country/site access. The server validates eligibility before saving and publishing.',
    none: 'None', sla: 'SLA (elapsed hours)', slaHint: 'Deadline configuration; delivery and escalation support depend on the module adapter.',
    signature: 'Signature required', self: 'Prevent self-approval', distinct: 'Different reviewer from earlier stages', addStage: 'Add stage', removeStage: 'Remove stage',
    reason: 'Change reason', reasonHint: 'Required for publication and retirement; retained in history.', save: 'Save draft', saving: 'Working…', saved: 'Draft saved. Review and simulate before publishing.',
    committed: 'Server confirmed the change.', failed: 'The operation failed. Refresh and review the latest policy before retrying.',
    validation: 'Enter a name, a valid priority, a change reason and 1–5 named stages. Choose exactly one reviewer per stage; SLA must be positive.',
    effective: 'Effective from (optional)', effectiveHint: 'Leave blank to publish now. Date and time use your local timezone.', separatePublisher: 'A different authorised administrator must publish this draft.', reviewTitle: 'Review policy change', reviewHint: 'New submissions use the published policy. Existing approvals retain their original route. Retirement preserves history.',
    confirm: 'Confirm', cancel: 'Cancel', version: 'Version', scope: 'Scope', updated: 'Updated', actions: 'Actions',
    simulation: 'Routing simulation', simulationHint: 'Server evaluation of these inputs. A saved draft can be included for review; simulation never submits or approves a record.',
    includeDraft: 'Include the saved draft', unsaved: 'Save changes before simulating this draft or publishing.', run: 'Simulate',
    matched: 'Selected policy', no_route: 'No matching policy. An enforced module requires an administrator to resolve routing; this is not automatic approval.',
    ambiguous: 'Routing is ambiguous. Resolve overlapping policies before using this route.', legacy: 'Existing module rules', enforced: 'Policy enforcement', mode: 'Module mode',
    matchStrength: 'Matching conditions', lowerRank: 'Lower precedence', topRank: 'Highest precedence', candidates: 'Matching candidates', eventsEmpty: 'No events found.', actor: 'Actor', userUnknown: 'Former or unavailable user',
    peopleSearch: 'Search people by name, role or site', anyScope: 'Organisation-wide', noPeople: 'No matching active people',
  },
  ar: {
    title: 'مصفوفة الموافقات', subtitle: 'سياسات موحدة للويب والجوال. تفوز الأولوية الأعلى ثم عدد شروط المطابقة. يمنع نشر السياسات المتداخلة المتساوية في الترتيب.',
    refresh: 'تحديث', retry: 'إعادة المحاولة', loading: 'جارٍ التحميل…', unavailable: 'إعداد الموافقات غير متاح. تحقق من الصلاحيات وجاهزية الخدمة ثم أعد المحاولة.',
    partial: 'تعذر التحقق من الأشخاص أو المواقع أو الأدوار. تم تعطيل التعديلات حتى تحميل البيانات المرجعية.',
    policies: 'السياسات', search: 'البحث في السياسات', all: 'الكل', draft_saved: 'تم حفظ المسودة', draft: 'مسودة', published: 'منشورة', retired: 'مؤرشفة',
    empty: 'لا توجد سياسات مطابقة لهذا النطاق. استخدم المحاكاة للتحقق من وضع الوحدة. أرشفة آخر سياسة لا تعطل تطبيق الموافقات.',
    inspection: 'فحص الإطارات', checklist: 'قائمة الفحص', work_order: 'تنفيذ أمر العمل', tyre_change: 'تنفيذ عملية الإطار', unsupported: 'تظل موافقة الحوادث خاضعة لقواعد الوحدة الحالية.',
    edit: 'تعديل المسودة', clone: 'نسخ كمسودة', history: 'السجل', publish: 'نشر', retire: 'أرشفة', close: 'إغلاق',
    new: 'سياسة جديدة', editor: 'مسودة السياسة', name: 'اسم السياسة', type: 'الوحدة', country: 'الدولة', anyCountry: 'أي دولة',
    site: 'الموقع', anySite: 'أي موقع', countryFirst: 'اختر الدولة قبل تحديد الموقع.', role: 'دور مقدم الطلب', person: 'مقدم الطلب',
    anyRole: 'أي دور', anyPerson: 'أي شخص', priority: 'الأولوية', priorityHint: 'الأرقام الأعلى لها الأسبقية. يرفض الخادم التداخلات الغامضة.',
    stages: 'مراحل المراجعة المتتابعة', stage: 'المرحلة', stageName: 'اسم المرحلة', reviewerRole: 'دور المراجع', reviewerPerson: 'مراجع محدد',
    eligibilityHint: 'يجب أن يمتلك المراجع صلاحية الوحدة الحالية ونطاق الدولة والموقع المناسبين. يتحقق الخادم من الأهلية قبل الحفظ والنشر.',
    none: 'لا يوجد', sla: 'المهلة بالساعات الفعلية', slaHint: 'إعداد المهلة؛ دعم الإشعارات والتصعيد يعتمد على تكامل الوحدة.',
    signature: 'التوقيع مطلوب', self: 'منع الموافقة الذاتية', distinct: 'مراجع مختلف عن المراحل السابقة', addStage: 'إضافة مرحلة', removeStage: 'حذف المرحلة',
    reason: 'سبب التغيير', reasonHint: 'مطلوب للنشر والأرشفة ويُحفظ في السجل.', save: 'حفظ المسودة', saving: 'جارٍ التنفيذ…', saved: 'تم حفظ المسودة. راجع وحاكِ المسار قبل النشر.',
    committed: 'أكد الخادم التغيير.', failed: 'تعذرت العملية. حدّث الصفحة وراجع أحدث نسخة قبل إعادة المحاولة.',
    validation: 'أدخل الاسم والأولوية الصحيحة وسبب التغيير ومن مرحلة إلى خمس مراحل مسماة. اختر مراجعاً واحداً لكل مرحلة؛ يجب أن تكون المهلة موجبة.',
    effective: 'يبدأ التطبيق من (اختياري)', effectiveHint: 'اتركه فارغاً للنشر الآن. التاريخ والوقت حسب منطقتك الزمنية المحلية.', separatePublisher: 'يجب أن ينشر هذه المسودة مسؤول آخر مخوّل.', reviewTitle: 'مراجعة تغيير السياسة', reviewHint: 'تستخدم الطلبات الجديدة السياسة المنشورة. تحتفظ الموافقات القائمة بمسارها الأصلي. الأرشفة تحفظ السجل.',
    confirm: 'تأكيد', cancel: 'إلغاء', version: 'الإصدار', scope: 'النطاق', updated: 'آخر تحديث', actions: 'الإجراءات',
    simulation: 'محاكاة مسار الموافقة', simulationHint: 'تقييم الخادم لهذه المدخلات. يمكن تضمين مسودة محفوظة للمراجعة؛ المحاكاة لا تقدم طلباً ولا توافق عليه.',
    includeDraft: 'تضمين المسودة المحفوظة', unsaved: 'احفظ التغييرات قبل محاكاة المسودة أو نشرها.', run: 'محاكاة',
    matched: 'السياسة المختارة', no_route: 'لا توجد سياسة مطابقة. تتطلب الوحدة المفعلة معالجة المسار بواسطة المسؤول؛ هذا ليس موافقة تلقائية.',
    ambiguous: 'مسار الموافقة غامض. عالج تداخل السياسات قبل استخدام المسار.', legacy: 'قواعد الوحدة الحالية', enforced: 'تطبيق السياسة', mode: 'وضع الوحدة',
    matchStrength: 'شروط المطابقة', lowerRank: 'أسبقية أقل', topRank: 'الأسبقية الأعلى', candidates: 'السياسات المطابقة', eventsEmpty: 'لا توجد أحداث.', actor: 'المنفذ', userUnknown: 'مستخدم سابق أو غير متاح',
    peopleSearch: 'البحث عن شخص بالاسم أو الدور أو الموقع', anyScope: 'على مستوى المؤسسة', noPeople: 'لا يوجد أشخاص نشطون مطابقون',
  },
}
