// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Every rectangle here is the audited position of one body
// component on the vehicle artwork, in the view's own 0..1 space.
// It is generated from the Flutter catalog
// (tyre_pulse_flutter/lib/features/accidents/domain/accident_damage_map.dart)
// so a mark placed on the phone lands on the same component here.
// Regenerate with scripts/genVehicleDamageZones.py after changing that file.

/** Every zone, grouped by the asset class its geometry was drawn for. */
export const ZONE_CATALOGS = Object.freeze({
  roadVehicle: Object.freeze([
    { id: 'front_windshield', view: 'front', left: 0.27, top: 0.27, width: 0.46, height: 0.2 },
    { id: 'front_hood', view: 'front', left: 0.38, top: 0.49, width: 0.24, height: 0.13 },
    { id: 'front_left_light', view: 'front', left: 0.25, top: 0.51, width: 0.12, height: 0.12 },
    { id: 'front_right_light', view: 'front', left: 0.63, top: 0.51, width: 0.12, height: 0.12 },
    { id: 'front_bumper', view: 'front', left: 0.26, top: 0.65, width: 0.48, height: 0.11 },
    { id: 'rear_windshield', view: 'rear', left: 0.28, top: 0.27, width: 0.44, height: 0.2 },
    { id: 'rear_tailgate', view: 'rear', left: 0.36, top: 0.49, width: 0.28, height: 0.15 },
    { id: 'rear_left_light', view: 'rear', left: 0.25, top: 0.5, width: 0.1, height: 0.15 },
    { id: 'rear_right_light', view: 'rear', left: 0.65, top: 0.5, width: 0.1, height: 0.15 },
    { id: 'rear_bumper', view: 'rear', left: 0.27, top: 0.67, width: 0.46, height: 0.09 },
    { id: 'left_front_door', view: 'left', left: 0.56, top: 0.36, width: 0.15, height: 0.23 },
    { id: 'left_rear_door', view: 'left', left: 0.4, top: 0.36, width: 0.15, height: 0.23 },
    { id: 'left_front_fender', view: 'left', left: 0.72, top: 0.5, width: 0.12, height: 0.15 },
    { id: 'left_rear_fender', view: 'left', left: 0.24, top: 0.5, width: 0.15, height: 0.15 },
    { id: 'left_side_panel', view: 'left', left: 0.12, top: 0.36, width: 0.27, height: 0.13 },
    { id: 'left_mirror', view: 'left', left: 0.72, top: 0.34, width: 0.08, height: 0.12 },
    { id: 'left_roof', view: 'left', left: 0.28, top: 0.27, width: 0.43, height: 0.08 },
    { id: 'right_front_door', view: 'right', left: 0.29, top: 0.36, width: 0.15, height: 0.23 },
    { id: 'right_rear_door', view: 'right', left: 0.45, top: 0.36, width: 0.15, height: 0.23 },
    { id: 'right_front_fender', view: 'right', left: 0.16, top: 0.5, width: 0.12, height: 0.15 },
    { id: 'right_rear_fender', view: 'right', left: 0.61, top: 0.5, width: 0.15, height: 0.15 },
    { id: 'right_side_panel', view: 'right', left: 0.61, top: 0.36, width: 0.27, height: 0.13 },
    { id: 'right_mirror', view: 'right', left: 0.2, top: 0.34, width: 0.08, height: 0.12 },
    { id: 'right_roof', view: 'right', left: 0.29, top: 0.27, width: 0.43, height: 0.08 },
    { id: 'top_hood', view: 'top', left: 0.35, top: 0.16, width: 0.3, height: 0.18 },
    { id: 'top_roof', view: 'top', left: 0.31, top: 0.35, width: 0.38, height: 0.34 },
    { id: 'top_tailgate', view: 'top', left: 0.35, top: 0.7, width: 0.3, height: 0.16 },
  ]),
  bus: Object.freeze([
    { id: 'front_windshield', view: 'front', left: 0.27, top: 0.27, width: 0.46, height: 0.2 },
    { id: 'front_cab_panel', view: 'front', left: 0.38, top: 0.49, width: 0.24, height: 0.13 },
    { id: 'front_left_light', view: 'front', left: 0.25, top: 0.51, width: 0.12, height: 0.12 },
    { id: 'front_right_light', view: 'front', left: 0.63, top: 0.51, width: 0.12, height: 0.12 },
    { id: 'front_bumper', view: 'front', left: 0.26, top: 0.65, width: 0.48, height: 0.11 },
    { id: 'rear_windshield', view: 'rear', left: 0.28, top: 0.27, width: 0.44, height: 0.2 },
    { id: 'rear_body_panel', view: 'rear', left: 0.36, top: 0.49, width: 0.28, height: 0.15 },
    { id: 'rear_left_light', view: 'rear', left: 0.25, top: 0.5, width: 0.1, height: 0.15 },
    { id: 'rear_right_light', view: 'rear', left: 0.65, top: 0.5, width: 0.1, height: 0.15 },
    { id: 'rear_bumper', view: 'rear', left: 0.27, top: 0.67, width: 0.46, height: 0.09 },
    { id: 'left_driver_door', view: 'left', left: 0.7, top: 0.37, width: 0.13, height: 0.23 },
    { id: 'left_passenger_door', view: 'left', left: 0.56, top: 0.37, width: 0.13, height: 0.23 },
    { id: 'left_body_panel', view: 'left', left: 0.18, top: 0.36, width: 0.37, height: 0.24 },
    { id: 'left_front_fender', view: 'left', left: 0.72, top: 0.61, width: 0.12, height: 0.1 },
    { id: 'left_rear_fender', view: 'left', left: 0.24, top: 0.61, width: 0.15, height: 0.1 },
    { id: 'left_mirror', view: 'left', left: 0.84, top: 0.35, width: 0.07, height: 0.12 },
    { id: 'left_roof', view: 'left', left: 0.22, top: 0.27, width: 0.61, height: 0.08 },
    { id: 'right_driver_door', view: 'right', left: 0.17, top: 0.37, width: 0.13, height: 0.23 },
    { id: 'right_passenger_door', view: 'right', left: 0.31, top: 0.37, width: 0.13, height: 0.23 },
    { id: 'right_body_panel', view: 'right', left: 0.45, top: 0.36, width: 0.37, height: 0.24 },
    { id: 'right_front_fender', view: 'right', left: 0.16, top: 0.61, width: 0.12, height: 0.1 },
    { id: 'right_rear_fender', view: 'right', left: 0.61, top: 0.61, width: 0.15, height: 0.1 },
    { id: 'right_mirror', view: 'right', left: 0.09, top: 0.35, width: 0.07, height: 0.12 },
    { id: 'right_roof', view: 'right', left: 0.17, top: 0.27, width: 0.61, height: 0.08 },
    { id: 'top_front_cab', view: 'top', left: 0.31, top: 0.12, width: 0.38, height: 0.2 },
    { id: 'top_passenger_body', view: 'top', left: 0.31, top: 0.33, width: 0.38, height: 0.54 },
  ]),
  heavyTruck: Object.freeze([
    { id: 'front_windshield', view: 'front', left: 0.31, top: 0.29, width: 0.38, height: 0.18 },
    { id: 'front_cab_panel', view: 'front', left: 0.39, top: 0.49, width: 0.22, height: 0.13 },
    { id: 'front_left_light', view: 'front', left: 0.29, top: 0.5, width: 0.09, height: 0.13 },
    { id: 'front_right_light', view: 'front', left: 0.62, top: 0.5, width: 0.09, height: 0.13 },
    { id: 'front_bumper', view: 'front', left: 0.29, top: 0.65, width: 0.42, height: 0.1 },
    { id: 'rear_equipment', view: 'rear', left: 0.35, top: 0.31, width: 0.3, height: 0.3 },
    { id: 'rear_left_light', view: 'rear', left: 0.24, top: 0.55, width: 0.1, height: 0.12 },
    { id: 'rear_right_light', view: 'rear', left: 0.66, top: 0.55, width: 0.1, height: 0.12 },
    { id: 'rear_bumper', view: 'rear', left: 0.29, top: 0.68, width: 0.42, height: 0.09 },
    { id: 'left_cab', view: 'left', left: 0.04, top: 0.37, width: 0.2, height: 0.21 },
    { id: 'left_boom', view: 'left', left: 0.25, top: 0.3, width: 0.68, height: 0.13 },
    { id: 'left_equipment_body', view: 'left', left: 0.26, top: 0.44, width: 0.66, height: 0.13 },
    { id: 'left_outrigger', view: 'left', left: 0.23, top: 0.58, width: 0.1, height: 0.1 },
    { id: 'right_cab', view: 'right', left: 0.76, top: 0.37, width: 0.2, height: 0.21 },
    { id: 'right_boom', view: 'right', left: 0.07, top: 0.3, width: 0.68, height: 0.13 },
    { id: 'right_equipment_body', view: 'right', left: 0.08, top: 0.44, width: 0.66, height: 0.13 },
    { id: 'right_outrigger', view: 'right', left: 0.67, top: 0.58, width: 0.1, height: 0.1 },
    { id: 'top_cab', view: 'top', left: 0.08, top: 0.35, width: 0.18, height: 0.3 },
    { id: 'top_boom', view: 'top', left: 0.28, top: 0.35, width: 0.58, height: 0.3 },
    { id: 'top_rear_equipment', view: 'top', left: 0.87, top: 0.38, width: 0.08, height: 0.24 },
  ]),
  loader: Object.freeze([
    { id: 'front_bucket', view: 'front', left: 0.2, top: 0.57, width: 0.6, height: 0.18 },
    { id: 'front_boom', view: 'front', left: 0.25, top: 0.4, width: 0.5, height: 0.15 },
    { id: 'front_cab', view: 'front', left: 0.36, top: 0.23, width: 0.28, height: 0.16 },
    { id: 'rear_counterweight', view: 'rear', left: 0.25, top: 0.48, width: 0.5, height: 0.18 },
    { id: 'rear_left_light', view: 'rear', left: 0.24, top: 0.37, width: 0.1, height: 0.1 },
    { id: 'rear_right_light', view: 'rear', left: 0.66, top: 0.37, width: 0.1, height: 0.1 },
    { id: 'left_bucket', view: 'left', left: 0.02, top: 0.49, width: 0.2, height: 0.18 },
    { id: 'left_lift_arm', view: 'left', left: 0.22, top: 0.39, width: 0.2, height: 0.11 },
    { id: 'left_front_wheel', view: 'left', left: 0.25, top: 0.51, width: 0.18, height: 0.17 },
    { id: 'left_cab', view: 'left', left: 0.43, top: 0.31, width: 0.18, height: 0.23 },
    { id: 'left_engine_cover', view: 'left', left: 0.62, top: 0.37, width: 0.25, height: 0.14 },
    { id: 'left_rear_wheel', view: 'left', left: 0.64, top: 0.52, width: 0.18, height: 0.17 },
    { id: 'right_bucket', view: 'right', left: 0.78, top: 0.49, width: 0.2, height: 0.18 },
    { id: 'right_lift_arm', view: 'right', left: 0.58, top: 0.39, width: 0.2, height: 0.11 },
    { id: 'right_front_wheel', view: 'right', left: 0.57, top: 0.51, width: 0.18, height: 0.17 },
    { id: 'right_cab', view: 'right', left: 0.39, top: 0.31, width: 0.17, height: 0.23 },
    { id: 'right_engine_cover', view: 'right', left: 0.13, top: 0.37, width: 0.25, height: 0.14 },
    { id: 'right_rear_wheel', view: 'right', left: 0.18, top: 0.52, width: 0.18, height: 0.17 },
    { id: 'top_bucket', view: 'top', left: 0.05, top: 0.3, width: 0.2, height: 0.4 },
    { id: 'top_lift_arm', view: 'top', left: 0.27, top: 0.34, width: 0.2, height: 0.32 },
    { id: 'top_cab', view: 'top', left: 0.49, top: 0.3, width: 0.2, height: 0.4 },
    { id: 'top_engine_cover', view: 'top', left: 0.71, top: 0.32, width: 0.23, height: 0.36 },
  ]),
  fixedEquipment: Object.freeze([
    { id: 'front_equipment_panel', view: 'front', left: 0.22, top: 0.28, width: 0.52, height: 0.42 },
    { id: 'front_pipework', view: 'front', left: 0.75, top: 0.34, width: 0.1, height: 0.3 },
    { id: 'front_base_frame', view: 'front', left: 0.22, top: 0.71, width: 0.63, height: 0.08 },
    { id: 'rear_equipment_panel', view: 'rear', left: 0.26, top: 0.28, width: 0.48, height: 0.42 },
    { id: 'rear_pipework', view: 'rear', left: 0.15, top: 0.34, width: 0.1, height: 0.3 },
    { id: 'rear_base_frame', view: 'rear', left: 0.15, top: 0.71, width: 0.63, height: 0.08 },
    { id: 'left_equipment_panel', view: 'left', left: 0.2, top: 0.31, width: 0.55, height: 0.36 },
    { id: 'left_control_panel', view: 'left', left: 0.76, top: 0.35, width: 0.1, height: 0.24 },
    { id: 'left_base_frame', view: 'left', left: 0.2, top: 0.68, width: 0.66, height: 0.08 },
    { id: 'right_equipment_panel', view: 'right', left: 0.25, top: 0.31, width: 0.55, height: 0.36 },
    { id: 'right_control_panel', view: 'right', left: 0.14, top: 0.35, width: 0.1, height: 0.24 },
    { id: 'right_base_frame', view: 'right', left: 0.14, top: 0.68, width: 0.66, height: 0.08 },
    { id: 'top_equipment_body', view: 'top', left: 0.22, top: 0.2, width: 0.56, height: 0.6 },
    { id: 'top_pipework', view: 'top', left: 0.79, top: 0.28, width: 0.1, height: 0.44 },
  ]),
  legacy: Object.freeze([
    { id: 'front_bumper', view: 'front', left: 0.12, top: 0.72, width: 0.76, height: 0.14 },
    { id: 'front_hood', view: 'front', left: 0.2, top: 0.4, width: 0.6, height: 0.3 },
    { id: 'front_windshield', view: 'front', left: 0.2, top: 0.17, width: 0.6, height: 0.18 },
    { id: 'front_left_light', view: 'front', left: 0.12, top: 0.46, width: 0.08, height: 0.16 },
    { id: 'front_right_light', view: 'front', left: 0.8, top: 0.46, width: 0.08, height: 0.16 },
    { id: 'rear_bumper', view: 'rear', left: 0.12, top: 0.72, width: 0.76, height: 0.14 },
    { id: 'rear_tailgate', view: 'rear', left: 0.2, top: 0.4, width: 0.6, height: 0.3 },
    { id: 'rear_windshield', view: 'rear', left: 0.2, top: 0.17, width: 0.6, height: 0.18 },
    { id: 'rear_left_light', view: 'rear', left: 0.12, top: 0.46, width: 0.08, height: 0.16 },
    { id: 'rear_right_light', view: 'rear', left: 0.8, top: 0.46, width: 0.08, height: 0.16 },
    { id: 'left_front_fender', view: 'left', left: 0.64, top: 0.4, width: 0.054, height: 0.22 },
    { id: 'left_front_door', view: 'left', left: 0.7, top: 0.34, width: 0.28, height: 0.26 },
    { id: 'left_rear_door', view: 'left', left: 0.32, top: 0.3, width: 0.3, height: 0.3 },
    { id: 'left_rear_fender', view: 'left', left: 0.04, top: 0.3, width: 0.274, height: 0.3 },
    { id: 'left_mirror', view: 'left', left: 0.92, top: 0.12, width: 0.07, height: 0.14 },
    { id: 'left_roof', view: 'left', left: 0.7, top: 0.04, width: 0.28, height: 0.08 },
    { id: 'right_front_fender', view: 'right', left: 0.3, top: 0.4, width: 0.06, height: 0.22 },
    { id: 'right_front_door', view: 'right', left: 0.02, top: 0.34, width: 0.274, height: 0.26 },
    { id: 'right_rear_door', view: 'right', left: 0.38, top: 0.3, width: 0.294, height: 0.3 },
    { id: 'right_rear_fender', view: 'right', left: 0.68, top: 0.3, width: 0.28, height: 0.3 },
    { id: 'right_mirror', view: 'right', left: 0.01, top: 0.12, width: 0.07, height: 0.14 },
    { id: 'right_roof', view: 'right', left: 0.02, top: 0.04, width: 0.28, height: 0.08 },
    { id: 'top_roof', view: 'top', left: 0.3, top: 0.06, width: 0.4, height: 0.22 },
    { id: 'top_tailgate', view: 'top', left: 0.3, top: 0.3, width: 0.4, height: 0.64 },
  ]),
})

/** The component name shown for a zone, as the phone words it. */
export const ZONE_LABELS = Object.freeze({
  front_base_frame: 'Base frame',
  front_boom: 'Boom',
  front_bucket: 'Bucket',
  front_bumper: 'Front bumper',
  front_cab: 'Cab',
  front_cab_panel: 'Cab front panel',
  front_equipment_panel: 'Equipment panel',
  front_hood: 'Hood',
  front_left_light: 'Left headlight',
  front_pipework: 'Pipework',
  front_right_light: 'Right headlight',
  front_windshield: 'Windshield',
  left_base_frame: 'Base frame',
  left_body_panel: 'Body panel',
  left_boom: 'Boom',
  left_bucket: 'Bucket',
  left_cab: 'Cab',
  left_control_panel: 'Control panel',
  left_driver_door: 'Driver door',
  left_engine_cover: 'Engine cover',
  left_equipment_body: 'Equipment body',
  left_equipment_panel: 'Equipment panel',
  left_front_door: 'Front door',
  left_front_fender: 'Front fender',
  left_front_wheel: 'Front wheel area',
  left_lift_arm: 'Lift arm',
  left_mirror: 'Side mirror',
  left_outrigger: 'Outrigger',
  left_passenger_door: 'Passenger door',
  left_rear_door: 'Rear door',
  left_rear_fender: 'Rear fender',
  left_rear_wheel: 'Rear wheel area',
  left_roof: 'Roof',
  left_side_panel: 'Side panel',
  rear_base_frame: 'Base frame',
  rear_body_panel: 'Body panel',
  rear_bumper: 'Rear bumper',
  rear_counterweight: 'Counterweight',
  rear_equipment: 'Equipment body',
  rear_equipment_panel: 'Equipment panel',
  rear_left_light: 'Left tail light',
  rear_pipework: 'Pipework',
  rear_right_light: 'Right tail light',
  rear_tailgate: 'Tailgate',
  rear_windshield: 'Rear glass',
  right_base_frame: 'Base frame',
  right_body_panel: 'Body panel',
  right_boom: 'Boom',
  right_bucket: 'Bucket',
  right_cab: 'Cab',
  right_control_panel: 'Control panel',
  right_driver_door: 'Driver door',
  right_engine_cover: 'Engine cover',
  right_equipment_body: 'Equipment body',
  right_equipment_panel: 'Equipment panel',
  right_front_door: 'Front door',
  right_front_fender: 'Front fender',
  right_front_wheel: 'Front wheel area',
  right_lift_arm: 'Lift arm',
  right_mirror: 'Side mirror',
  right_outrigger: 'Outrigger',
  right_passenger_door: 'Passenger door',
  right_rear_door: 'Rear door',
  right_rear_fender: 'Rear fender',
  right_rear_wheel: 'Rear wheel area',
  right_roof: 'Roof',
  right_side_panel: 'Side panel',
  top_boom: 'Boom',
  top_bucket: 'Bucket',
  top_cab: 'Cab',
  top_engine_cover: 'Engine cover',
  top_equipment_body: 'Equipment body',
  top_front_cab: 'Cab',
  top_hood: 'Hood',
  top_lift_arm: 'Lift arm',
  top_passenger_body: 'Passenger body',
  top_pipework: 'Pipework',
  top_rear_equipment: 'Equipment body',
  top_roof: 'Roof',
  top_tailgate: 'Tailgate',
})
