import XLSX from 'xlsx'
import fs from 'node:fs'
const wb = XLSX.read(fs.readFileSync(process.argv[2]), {type:'buffer'})
const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], {defval:null})
fs.writeFileSync(process.argv[3], JSON.stringify(rows,null,1))
console.log('rows', rows.length)
console.log('distinct policy', [...new Set(rows.map(r=>r.POLICY_NO))])
console.log('distinct claim_type', [...new Set(rows.map(r=>r.CLAIM_TYPE))])
console.log('distinct uw_year', [...new Set(rows.map(r=>r.UW_YEAR))])
const ids = rows.map(r=>r.CLAIM_NO+'|'+(r.SUB_CLAIM_NUMBER||''))
console.log('distinct keys', new Set(ids).size)
console.log('dup claim_no', Object.entries(rows.reduce((a,r)=>{a[r.CLAIM_NO]=(a[r.CLAIM_NO]||0)+1;return a},{})).filter(([,v])=>v>1))
console.log('null chassis', rows.filter(r=>!r.CHASSIS_NO).length, 'null plate', rows.filter(r=>!r.VEHICLE_PLATE_NO).length, 'null est', rows.filter(r=>r.ESTIMATE_PAYMENT==null).length)
console.log('sample dates', rows.slice(0,3).map(r=>[r.INTIMATION_DATE, r.ACCIDENT_DATE]))
console.log('total estimate', rows.reduce((a,r)=>a+(Number(r.ESTIMATE_PAYMENT)||0),0))
