/// Localised copy used only by the extended source-only accident-case preview.
///
/// The existing accident ARB catalog predates the end-to-end case workflow.
/// This small feature-local catalog keeps the new surface translated in all
/// three shipped locales without changing the shared generated localisation
/// files owned by the application shell.
library;

import 'package:flutter/widgets.dart';

final class AccidentCaseWorkflowCopy {
  factory AccidentCaseWorkflowCopy.of(BuildContext context) {
    final String language = Localizations.localeOf(context).languageCode;
    return AccidentCaseWorkflowCopy._(
      _catalogs[language] ?? _catalogs['en']!,
    );
  }

  const AccidentCaseWorkflowCopy._(this._values);

  final Map<String, String> _values;

  String call(String key) => _values[key] ?? key;

  String evidenceLinked(int count) => call(
        count == 1 ? 'evidenceLinkedOne' : 'evidenceLinkedMany',
      ).replaceAll('%count%', '$count');

  String notificationCount(int count) => call(
        count == 1 ? 'notificationCountOne' : 'notificationCountMany',
      ).replaceAll('%count%', '$count');

  static const Map<String, Map<String, String>> _catalogs =
      <String, Map<String, String>>{
    'en': <String, String>{
      'fleetHint':
          'Fleet identity, location and ownership from the case record',
      'validationFacts': 'Validation facts',
      'recorded': 'Recorded',
      'missing': 'Missing',
      'workstreamControl': 'Workstream control',
      'status': 'Status',
      'required': 'Required',
      'notRequired': 'Not required',
      'requirementUnknown': 'Route requirement not recorded',
      'owningTeam': 'Owning team',
      'ownerRole': 'Owner role',
      'recordedProgress': 'Recorded progress',
      'lastUpdate': 'Last update',
      'workstreamNotes': 'Workstream notes',
      'responsibilityTitle': 'Responsibility, payer & documents',
      'responsibilityHint':
          'Liability and payment remain separate until their decisions are recorded.',
      'documentsTitle': 'Document control',
      'documentsUnavailable':
          'The document checklist, verification state and authority files are not included in this mobile read model.',
      'evidenceLinkedOne': '%count% evidence file is linked to the incident.',
      'evidenceLinkedMany':
          '%count% evidence files are linked to the incident.',
      'noEvidenceLinked': 'No evidence files are linked to the incident.',
      'assessmentHint': 'Damage, estimate and the recommended repair path',
      'repairPlanTitle': 'Repair route, quotation & PO',
      'repairPlanHint':
          'Route selection and procurement approvals are controlled server actions.',
      'quotation': 'Quotation comparison',
      'purchaseOrder': 'Purchase order',
      'notInReadModel': 'Not available in this mobile read model',
      'handoverTitle': 'Workshop QC & Fleet handover',
      'handoverHint':
          'Workshop completion and Fleet acceptance are recorded separately.',
      'slaTitle': 'SLA & accountable owner',
      'slaHint':
          'SLA clocks start and stop from server transitions, not from this screen.',
      'slaUnavailable':
          'No SLA instance, due time or pause history is included in this mobile read model.',
      'currentOwner': 'Current owner',
      'noActiveOwner': 'No active workstream owner is recorded.',
      'routeCompletion': 'Route completion',
      'routeCompletionUnavailable': 'Route-based completion is not recorded.',
      'timelineTitle': 'Workstream updates',
      'timelineHint': 'Latest dated update from each workstream',
      'timelineEmpty': 'No dated workstream updates are recorded.',
      'notificationsTitle': 'Notifications & email',
      'notificationsHint': 'Case-linked in-app notifications for your account',
      'notificationsNoWorkspace':
          'Sign-in context is unavailable, so notifications were not queried.',
      'notificationsLoading': 'Loading case notifications…',
      'notificationsFailed': 'Case notifications could not be loaded.',
      'notificationsEmpty': 'No case-linked notifications are in your inbox.',
      'notificationCountOne': '%count% case notification',
      'notificationCountMany': '%count% case notifications',
      'emailUnavailable':
          'Email enablement and delivery history are controlled by the server and are not included in this read model.',
      'unread': 'Unread',
      'read': 'Read',
      'localPreviewTitle': 'Local workflow preview',
      'localPreviewMessage':
          'Preview records and changes stay on this screen only. Nothing is submitted to Tyre Pulse.',
      'localChange': 'Local change',
      'responsibilityChoice': 'Responsibility decision',
      'payerChoice': 'Expected payer',
      'liabilityUnderInvestigation': 'Under investigation',
      'liabilityCompanyDriver': 'Company driver',
      'liabilityThirdParty': 'Third party',
      'liabilityShared': 'Shared liability',
      'liabilityOurDriverGcc': 'Our driver / GCC',
      'liabilityOtherParty': 'Other party',
      'liabilityNotApplicable': 'Not applicable',
      'payerInsurer': 'Insurer',
      'payerCompany': 'Company',
      'payerThirdParty': 'Third party',
      'payerOtherPartyInsurance': 'Other-party insurance',
      'payerOurInsurance': 'Our insurance',
      'payerGccCompany': 'GCC / company',
      'payerDriverRecovery': 'Driver recovery',
      'payerWarranty': 'Warranty',
      'payerPending': 'Pending',
      'liabilityPercent': 'Liability %',
      'provisionalAuditNote': 'Provisional / audit note',
      'responsibleCompany': 'Responsible company',
      'failedParty': 'Failed / responsible company',
      'documentRegister': 'Case document register',
      'document': 'Document',
      'reference': 'Reference',
      'updated': 'Updated',
      'authorityReport': 'Authority / police report',
      'driverStatement': 'Driver statement',
      'insurancePolicy': 'Insurance policy copy',
      'workshopAssessmentDocument': 'Workshop assessment',
      'repairQuotationDocument': 'Repair quotation',
      'purchaseOrderDocument': 'Purchase order',
      'policeReport': 'Police report',
      'najmReport': 'Najm report',
      'taqdeerAssessment': 'Taqdeer assessment / number',
      'thirdPartyRegistration': 'Third-party vehicle registration',
      'thirdPartyPolicy': 'Third-party insurance policy',
      'drivingLicence': 'Driving licence',
      'companyUndertaking': 'Company undertaking (optional)',
      'vehicleRegistration': 'Vehicle registration',
      'accidentPhotos': 'Accident photographs',
      'uploadedBy': 'Uploaded by',
      'mandatory': 'Mandatory',
      'optional': 'Optional',
      'statusComplete': 'Complete',
      'statusInProgress': 'In progress',
      'statusPending': 'Pending',
      'statusWarning': 'Attention',
      'statusMissing': 'Missing',
      'statusVerified': 'Verified',
      'statusDelivered': 'Delivered',
      'statusQueued': 'Queued',
      'statusScheduled': 'Scheduled',
      'statusSigned': 'Signed',
      'claimPackageTitle': 'Claim package',
      'claimPackageHint':
          'Policy, claim documents and insurer decision in one accountable pack',
      'claimRecoveryTitle': 'Settlement & recovery',
      'claimRecoveryHint':
          'Claimed, approved, received and outstanding amounts remain distinct',
      'insurerDecision': 'Insurer decision',
      'approvedForSettlement': 'Approved for settlement',
      'outstandingRecovery': 'Outstanding recovery',
      'previewAmount': 'Preview amount',
      'repairRouteDecision': 'Repair route decision',
      'internalWorkshop': 'Internal workshop',
      'authorisedDealer': 'Authorised dealer',
      'externalWorkshop': 'External workshop',
      'totalLoss': 'Total loss',
      'onSiteRepair': 'On-site repair',
      'safeToMove': 'Safe to move',
      'towingRequired': 'Tow required',
      'vehicleOffRoad': 'Vehicle off road (VOR)',
      'yes': 'Yes',
      'no': 'No',
      'labourHours': 'Estimated labour hours',
      'labourCost': 'Estimated labour cost',
      'partsAvailability': 'Parts availability',
      'partsCount': '%available% of %required% parts available',
      'workshopRecommendation': 'Workshop recommendation',
      'externalRepairFlow': 'External-workshop handoff',
      'externalRepairFlowHint':
          'Fleet / Workshop dispatches the vehicle. The vendor supplies its quotation after arrival; Tyre Pulse then records comparison and PO before repair starts.',
      'vehicleDispatchedMilestone': 'Vehicle dispatched to workshop',
      'externalWorkshopArrivalMilestone': 'External workshop arrival confirmed',
      'vendorQuotationReceivedMilestone': 'Vendor quotation received',
      'quotationComparedMilestone': 'Quotation compared and selected',
      'purchaseOrderRecordedMilestone': 'Purchase order recorded',
      'repairStartMilestone': 'Repair start confirmed',
      'fleetWorkshopCoordinator': 'Fleet / Workshop coordinator',
      'externalWorkshopCoordinator': 'External workshop coordinator',
      'handoffAt': 'Handoff time',
      'quotationRegister': 'Quotation comparison',
      'vendor': 'Vendor / source',
      'amount': 'Amount',
      'turnaround': 'Turnaround',
      'days': 'days',
      'selected': 'Selected',
      'internalWorkshopEstimate': 'Internal workshop estimate',
      'authorisedRepairCentre': 'Authorised repair centre',
      'purchaseOrderControl': 'Purchase-order control',
      'poReference': 'PO reference',
      'poOwner': 'PO owner',
      'recordPoRepairStart': 'Record purchase order locally',
      'startRepairLocally': 'Start repair locally after PO',
      'poRecordedLocal':
          'Purchase order recorded in this local preview. Repair can now start.',
      'repairStartedLocal': 'Repair start recorded in this local preview.',
      'procurementManager': 'Procurement Manager',
      'handoverReceipt': 'Handover receipt',
      'handoverChecklist': 'Fleet acceptance checklist',
      'repairScopeCompleted': 'Approved repair scope completed',
      'roadTestCompleted': 'Road test completed',
      'warningLightsClear': 'Dashboard warning lights clear',
      'handoverPhotosAttached': 'Handover photographs attached',
      'fleetAcceptance': 'Fleet acceptance recorded',
      'workshopSignature': 'Workshop signature',
      'fleetSignature': 'Fleet inspector signature',
      'pendingSignature': 'Pending signature',
      'receiptNumber': 'Receipt number',
      'toggleChecklistHint': 'Tap checklist rows to update this local preview.',
      'slaRegister': 'SLA ownership register',
      'assignedActors': 'Named accountable actors',
      'activity': 'Activity',
      'target': 'Target',
      'owner': 'Owner',
      'due': 'Due',
      'fleetValidationActivity': 'Fleet validation',
      'insuranceReviewActivity': 'Insurance review',
      'repairEstimateActivity': 'Initial repair estimate',
      'poAfterApprovalActivity': 'PO after approval',
      'fleetInspectionActivity': 'Fleet inspection after repair',
      'fourWorkingHours': '4 working hours',
      'oneBusinessDay': '1 business day',
      'twoBusinessDays': '2 business days',
      'fleetSupervisor': 'Fleet Supervisor',
      'insuranceClaimsOfficer': 'Insurance Claims Officer',
      'workshopPlanner': 'Workshop Planner',
      'procurementOfficer': 'Procurement Officer',
      'fleetInspector': 'Fleet Inspector',
      'pmvManager': 'PMV Manager',
      'fleetIncidentOfficer': 'Fleet Incident Officer',
      'hseOfficer': 'HSE Officer',
      'incidentSubmittedEvent': 'Incident submitted',
      'fleetValidatedEvent': 'Fleet validation completed',
      'liabilityReviewEvent': 'Liability review opened',
      'claimPackageEvent': 'Claim package prepared',
      'workshopAssessmentEvent': 'Workshop assessment scheduled',
      'closureApprovalAction': 'Final closure approval',
      'claimCompleteness': 'Claim-document completeness gate',
      'documentsVerified':
          '%verified% of %required% required documents verified',
      'claimReady': 'Claim package ready',
      'claimBlocked': 'Claim package blocked',
      'deductible': 'Deductible',
      'netClaimable': 'Net claimable',
      'financialClosure': 'Financial closure confirmed',
      'recoveryEditHint':
          'Recovery source, reference, date and amount become editable after financial closure.',
      'recoverySource': 'Recovery source',
      'recoveryReference': 'Recovery reference',
      'recoveryDate': 'Recovery date',
      'recoveryAmount': 'Recovery amount',
      'insuranceSettlement': 'Insurance settlement',
      'recoveryThirdParty': 'Third-party recovery',
      'recoveryDriver': 'Driver recovery',
      'recoveryWarranty': 'Warranty',
      'recoveryCompany': 'Company recovery',
      'deliveryLog': 'Notification delivery log',
      'recipientGroups': 'Recipient groups',
      'subject': 'Subject',
      'recipients': 'Recipients',
      'channel': 'Channel',
      'caseSubmittedSubject': 'Case submitted - validation required',
      'claimActionSubject': 'Claim package - action required',
      'repairApprovalSubject': 'Repair route - approval required',
      'dailyDigestSubject': 'Case activity daily digest',
      'fleetAndHseRecipients': 'Fleet Supervisor + HSE Officer',
      'insuranceRecipients': 'Insurance Claims + Insurance Manager',
      'repairApprovalRecipients': 'Fleet Manager + Workshop Manager',
      'caseMemberRecipients': 'Active case members',
      'inAppAndEmail': 'In-app + email',
      'inApp': 'In-app',
      'emailDigest': 'Email digest',
    },
    'ar': <String, String>{
      'fleetHint': 'هوية المركبة والموقع والمسؤولية من سجل القضية',
      'validationFacts': 'بيانات التحقق',
      'recorded': 'مسجل',
      'missing': 'مفقود',
      'workstreamControl': 'ضبط مسار العمل',
      'status': 'الحالة',
      'required': 'مطلوب',
      'notRequired': 'غير مطلوب',
      'requirementUnknown': 'متطلب المسار غير مسجل',
      'owningTeam': 'الفريق المسؤول',
      'ownerRole': 'دور المسؤول',
      'recordedProgress': 'التقدم المسجل',
      'lastUpdate': 'آخر تحديث',
      'workstreamNotes': 'ملاحظات مسار العمل',
      'responsibilityTitle': 'المسؤولية والجهة الدافعة والمستندات',
      'responsibilityHint':
          'تبقى المسؤولية والدفع منفصلين حتى تسجيل القرارات الخاصة بهما.',
      'documentsTitle': 'ضبط المستندات',
      'documentsUnavailable':
          'قائمة المستندات وحالة التحقق وتقارير الجهات غير مضمنة في نموذج القراءة على الجوال.',
      'evidenceLinkedOne': 'ملف دليل واحد مرتبط بالحادث.',
      'evidenceLinkedMany': '%count% ملفات أدلة مرتبطة بالحادث.',
      'noEvidenceLinked': 'لا توجد ملفات أدلة مرتبطة بالحادث.',
      'assessmentHint': 'الأضرار والتقدير ومسار الإصلاح الموصى به',
      'repairPlanTitle': 'مسار الإصلاح وعرض السعر وأمر الشراء',
      'repairPlanHint':
          'اختيار المسار واعتمادات المشتريات إجراءات خاضعة للخادم.',
      'quotation': 'مقارنة عروض الأسعار',
      'purchaseOrder': 'أمر الشراء',
      'notInReadModel': 'غير متاح في نموذج القراءة على الجوال',
      'handoverTitle': 'فحص الورشة وتسليم المركبة للأسطول',
      'handoverHint': 'يتم تسجيل إكمال الورشة وقبول الأسطول بشكل منفصل.',
      'slaTitle': 'اتفاقية الخدمة والمسؤول الحالي',
      'slaHint':
          'تبدأ مؤقتات الخدمة وتتوقف بانتقالات الخادم، وليس من هذه الشاشة.',
      'slaUnavailable':
          'لا يتضمن نموذج القراءة هذا مؤقت خدمة أو موعد استحقاق أو سجل إيقاف مؤقت.',
      'currentOwner': 'المسؤول الحالي',
      'noActiveOwner': 'لا يوجد مسؤول مسجل لمسار عمل نشط.',
      'routeCompletion': 'اكتمال المسار',
      'routeCompletionUnavailable': 'نسبة اكتمال المسار غير مسجلة.',
      'timelineTitle': 'تحديثات مسارات العمل',
      'timelineHint': 'آخر تحديث مؤرخ لكل مسار عمل',
      'timelineEmpty': 'لا توجد تحديثات مؤرخة لمسارات العمل.',
      'notificationsTitle': 'الإشعارات والبريد الإلكتروني',
      'notificationsHint': 'إشعارات داخل التطبيق مرتبطة بالقضية لحسابك',
      'notificationsNoWorkspace':
          'سياق تسجيل الدخول غير متاح، لذلك لم يتم الاستعلام عن الإشعارات.',
      'notificationsLoading': 'جارٍ تحميل إشعارات القضية…',
      'notificationsFailed': 'تعذر تحميل إشعارات القضية.',
      'notificationsEmpty': 'لا توجد إشعارات مرتبطة بالقضية في صندوقك.',
      'notificationCountOne': 'إشعار واحد للقضية',
      'notificationCountMany': '%count% إشعارات للقضية',
      'emailUnavailable':
          'تفعيل البريد وسجل التسليم يتحكم بهما الخادم ولا يظهران في نموذج القراءة هذا.',
      'unread': 'غير مقروء',
      'read': 'مقروء',
      'localPreviewTitle': 'معاينة محلية لسير العمل',
      'localPreviewMessage':
          'تبقى سجلات المعاينة والتغييرات على هذه الشاشة فقط. لا يتم إرسال أي شيء إلى Tyre Pulse.',
      'localChange': 'تغيير محلي',
      'responsibilityChoice': 'قرار المسؤولية',
      'payerChoice': 'الجهة الدافعة المتوقعة',
      'liabilityUnderInvestigation': 'قيد التحقيق',
      'liabilityCompanyDriver': 'سائق الشركة',
      'liabilityThirdParty': 'طرف ثالث',
      'liabilityShared': 'مسؤولية مشتركة',
      'liabilityOurDriverGcc': 'سائقنا / الشركة',
      'liabilityOtherParty': 'الطرف الآخر',
      'liabilityNotApplicable': 'لا ينطبق',
      'payerInsurer': 'شركة التأمين',
      'payerCompany': 'الشركة',
      'payerThirdParty': 'طرف ثالث',
      'payerOtherPartyInsurance': 'تأمين الطرف الآخر',
      'payerOurInsurance': 'تأميننا',
      'payerGccCompany': 'الشركة / GCC',
      'payerDriverRecovery': 'استرداد من السائق',
      'payerWarranty': 'الضمان',
      'payerPending': 'معلق',
      'liabilityPercent': 'نسبة المسؤولية',
      'provisionalAuditNote': 'ملاحظة مؤقتة / تدقيق',
      'responsibleCompany': 'الشركة المسؤولة',
      'failedParty': 'الشركة المتسببة / المسؤولة',
      'documentRegister': 'سجل مستندات القضية',
      'document': 'المستند',
      'reference': 'المرجع',
      'updated': 'آخر تحديث',
      'authorityReport': 'تقرير الجهة / الشرطة',
      'driverStatement': 'إفادة السائق',
      'insurancePolicy': 'نسخة وثيقة التأمين',
      'workshopAssessmentDocument': 'تقييم الورشة',
      'repairQuotationDocument': 'عرض سعر الإصلاح',
      'purchaseOrderDocument': 'أمر الشراء',
      'policeReport': 'تقرير الشرطة',
      'najmReport': 'تقرير نجم',
      'taqdeerAssessment': 'تقييم / رقم تقدير',
      'thirdPartyRegistration': 'استمارة مركبة الطرف الآخر',
      'thirdPartyPolicy': 'وثيقة تأمين الطرف الآخر',
      'drivingLicence': 'رخصة القيادة',
      'companyUndertaking': 'تعهد الشركة (اختياري)',
      'vehicleRegistration': 'استمارة المركبة',
      'accidentPhotos': 'صور الحادث',
      'uploadedBy': 'رفع بواسطة',
      'mandatory': 'إلزامي',
      'optional': 'اختياري',
      'statusComplete': 'مكتمل',
      'statusInProgress': 'قيد التنفيذ',
      'statusPending': 'معلق',
      'statusWarning': 'يحتاج انتباهًا',
      'statusMissing': 'مفقود',
      'statusVerified': 'تم التحقق',
      'statusDelivered': 'تم التسليم',
      'statusQueued': 'في قائمة الانتظار',
      'statusScheduled': 'مجدول',
      'statusSigned': 'موقّع',
      'claimPackageTitle': 'حزمة المطالبة',
      'claimPackageHint':
          'الوثيقة والمستندات وقرار شركة التأمين في حزمة مسؤولة واحدة',
      'claimRecoveryTitle': 'التسوية والاسترداد',
      'claimRecoveryHint':
          'تبقى المبالغ المطالب بها والمعتمدة والمستلمة والمتبقية منفصلة',
      'insurerDecision': 'قرار شركة التأمين',
      'approvedForSettlement': 'معتمد للتسوية',
      'outstandingRecovery': 'الاسترداد المتبقي',
      'previewAmount': 'مبلغ المعاينة',
      'repairRouteDecision': 'قرار مسار الإصلاح',
      'internalWorkshop': 'ورشة داخلية',
      'authorisedDealer': 'وكيل معتمد',
      'externalWorkshop': 'ورشة خارجية',
      'totalLoss': 'خسارة كلية',
      'onSiteRepair': 'إصلاح في الموقع',
      'safeToMove': 'آمنة للتحريك',
      'towingRequired': 'تحتاج سحبًا',
      'vehicleOffRoad': 'المركبة خارج الخدمة',
      'yes': 'نعم',
      'no': 'لا',
      'labourHours': 'ساعات العمل المقدرة',
      'labourCost': 'تكلفة العمل المقدرة',
      'partsAvailability': 'توفر القطع',
      'partsCount': '%available% من %required% قطع متاحة',
      'workshopRecommendation': 'توصية الورشة',
      'externalRepairFlow': 'تسليم الورشة الخارجية',
      'externalRepairFlowHint':
          'يرسل فريق الأسطول / الورشة المركبة، ثم تقدم الورشة الخارجية عرضها بعد الوصول، ويسجل Tyre Pulse المقارنة وأمر الشراء قبل بدء الإصلاح.',
      'vehicleDispatchedMilestone': 'تم إرسال المركبة إلى الورشة',
      'externalWorkshopArrivalMilestone': 'تم تأكيد وصول الورشة الخارجية',
      'vendorQuotationReceivedMilestone': 'تم استلام عرض المورد',
      'quotationComparedMilestone': 'تمت مقارنة العرض واختياره',
      'purchaseOrderRecordedMilestone': 'تم تسجيل أمر الشراء',
      'repairStartMilestone': 'تم تأكيد بدء الإصلاح',
      'fleetWorkshopCoordinator': 'منسق الأسطول / الورشة',
      'externalWorkshopCoordinator': 'منسق الورشة الخارجية',
      'handoffAt': 'وقت التسليم',
      'quotationRegister': 'مقارنة عروض الأسعار',
      'vendor': 'المورد / المصدر',
      'amount': 'المبلغ',
      'turnaround': 'مدة الإنجاز',
      'days': 'أيام',
      'selected': 'مختار',
      'internalWorkshopEstimate': 'تقدير الورشة الداخلية',
      'authorisedRepairCentre': 'مركز إصلاح معتمد',
      'purchaseOrderControl': 'ضبط أمر الشراء',
      'poReference': 'مرجع أمر الشراء',
      'poOwner': 'مسؤول أمر الشراء',
      'recordPoRepairStart': 'تسجيل أمر الشراء محليًا',
      'startRepairLocally': 'بدء الإصلاح محليًا بعد أمر الشراء',
      'poRecordedLocal':
          'تم تسجيل أمر الشراء في هذه المعاينة المحلية، ويمكن الآن بدء الإصلاح.',
      'repairStartedLocal': 'تم تسجيل بدء الإصلاح في هذه المعاينة المحلية.',
      'procurementManager': 'مدير المشتريات',
      'handoverReceipt': 'إيصال التسليم',
      'handoverChecklist': 'قائمة قبول الأسطول',
      'repairScopeCompleted': 'اكتمل نطاق الإصلاح المعتمد',
      'roadTestCompleted': 'اكتمل اختبار الطريق',
      'warningLightsClear': 'لمبات التحذير في لوحة القيادة سليمة',
      'handoverPhotosAttached': 'صور التسليم مرفقة',
      'fleetAcceptance': 'تم تسجيل قبول الأسطول',
      'workshopSignature': 'توقيع الورشة',
      'fleetSignature': 'توقيع مفتش الأسطول',
      'pendingSignature': 'بانتظار التوقيع',
      'receiptNumber': 'رقم الإيصال',
      'toggleChecklistHint': 'اضغط على بنود القائمة لتحديث المعاينة المحلية.',
      'slaRegister': 'سجل مسؤولية اتفاقية الخدمة',
      'assignedActors': 'المسؤولون المحددون بالاسم',
      'activity': 'النشاط',
      'target': 'الهدف',
      'owner': 'المسؤول',
      'due': 'الاستحقاق',
      'fleetValidationActivity': 'تحقق الأسطول',
      'insuranceReviewActivity': 'مراجعة التأمين',
      'repairEstimateActivity': 'تقدير الإصلاح الأولي',
      'poAfterApprovalActivity': 'أمر الشراء بعد الاعتماد',
      'fleetInspectionActivity': 'فحص الأسطول بعد الإصلاح',
      'fourWorkingHours': '4 ساعات عمل',
      'oneBusinessDay': 'يوم عمل واحد',
      'twoBusinessDays': 'يومان عمل',
      'fleetSupervisor': 'مشرف الأسطول',
      'insuranceClaimsOfficer': 'مسؤول مطالبات التأمين',
      'workshopPlanner': 'مخطط الورشة',
      'procurementOfficer': 'مسؤول المشتريات',
      'fleetInspector': 'مفتش الأسطول',
      'pmvManager': 'مدير المعدات والمركبات',
      'fleetIncidentOfficer': 'مسؤول حوادث الأسطول',
      'hseOfficer': 'مسؤول الصحة والسلامة',
      'incidentSubmittedEvent': 'تم إرسال الحادث',
      'fleetValidatedEvent': 'اكتمل تحقق الأسطول',
      'liabilityReviewEvent': 'فُتحت مراجعة المسؤولية',
      'claimPackageEvent': 'تم إعداد حزمة المطالبة',
      'workshopAssessmentEvent': 'تمت جدولة تقييم الورشة',
      'closureApprovalAction': 'اعتماد الإغلاق النهائي',
      'claimCompleteness': 'بوابة اكتمال مستندات المطالبة',
      'documentsVerified':
          'تم التحقق من %verified% من %required% مستندات مطلوبة',
      'claimReady': 'حزمة المطالبة جاهزة',
      'claimBlocked': 'حزمة المطالبة متوقفة',
      'deductible': 'التحمل',
      'netClaimable': 'صافي المطالبة',
      'financialClosure': 'تم تأكيد الإغلاق المالي',
      'recoveryEditHint':
          'يمكن تعديل مصدر الاسترداد ومرجعه وتاريخه ومبلغه بعد الإغلاق المالي.',
      'recoverySource': 'مصدر الاسترداد',
      'recoveryReference': 'مرجع الاسترداد',
      'recoveryDate': 'تاريخ الاسترداد',
      'recoveryAmount': 'مبلغ الاسترداد',
      'insuranceSettlement': 'تسوية التأمين',
      'recoveryThirdParty': 'استرداد من طرف ثالث',
      'recoveryDriver': 'استرداد من السائق',
      'recoveryWarranty': 'الضمان',
      'recoveryCompany': 'استرداد الشركة',
      'deliveryLog': 'سجل تسليم الإشعارات',
      'recipientGroups': 'مجموعات المستلمين',
      'subject': 'الموضوع',
      'recipients': 'المستلمون',
      'channel': 'القناة',
      'caseSubmittedSubject': 'تم إرسال القضية - التحقق مطلوب',
      'claimActionSubject': 'حزمة المطالبة - إجراء مطلوب',
      'repairApprovalSubject': 'مسار الإصلاح - اعتماد مطلوب',
      'dailyDigestSubject': 'الملخص اليومي لنشاط القضية',
      'fleetAndHseRecipients': 'مشرف الأسطول + مسؤول السلامة',
      'insuranceRecipients': 'مسؤول المطالبات + مدير التأمين',
      'repairApprovalRecipients': 'مدير الأسطول + مدير الورشة',
      'caseMemberRecipients': 'أعضاء القضية النشطون',
      'inAppAndEmail': 'داخل التطبيق + بريد إلكتروني',
      'inApp': 'داخل التطبيق',
      'emailDigest': 'ملخص بالبريد الإلكتروني',
    },
    'ur': <String, String>{
      'fleetHint': 'کیس ریکارڈ سے فلیٹ شناخت، مقام اور ذمہ داری',
      'validationFacts': 'تصدیقی معلومات',
      'recorded': 'درج شدہ',
      'missing': 'نامکمل',
      'workstreamControl': 'ورک اسٹریم کنٹرول',
      'status': 'حالت',
      'required': 'ضروری',
      'notRequired': 'ضروری نہیں',
      'requirementUnknown': 'روٹ کی ضرورت درج نہیں',
      'owningTeam': 'ذمہ دار ٹیم',
      'ownerRole': 'ذمہ دار کردار',
      'recordedProgress': 'درج شدہ پیش رفت',
      'lastUpdate': 'آخری تازہ کاری',
      'workstreamNotes': 'ورک اسٹریم نوٹس',
      'responsibilityTitle': 'ذمہ داری، ادائیگی اور دستاویزات',
      'responsibilityHint':
          'ذمہ داری اور ادائیگی کے فیصلے درج ہونے تک الگ رہتے ہیں۔',
      'documentsTitle': 'دستاویز کنٹرول',
      'documentsUnavailable':
          'دستاویز چیک لسٹ، تصدیقی حالت اور اتھارٹی فائلیں اس موبائل ریڈ ماڈل میں شامل نہیں۔',
      'evidenceLinkedOne': 'حادثے سے ایک ثبوت فائل منسلک ہے۔',
      'evidenceLinkedMany': 'حادثے سے %count% ثبوت فائلیں منسلک ہیں۔',
      'noEvidenceLinked': 'حادثے سے کوئی ثبوت فائل منسلک نہیں۔',
      'assessmentHint': 'نقصان، تخمینہ اور تجویز کردہ مرمتی راستہ',
      'repairPlanTitle': 'مرمتی راستہ، کوٹیشن اور خریداری آرڈر',
      'repairPlanHint':
          'راستے کا انتخاب اور خریداری کی منظوری سرور کے زیر کنٹرول ہیں۔',
      'quotation': 'کوٹیشن کا موازنہ',
      'purchaseOrder': 'خریداری آرڈر',
      'notInReadModel': 'اس موبائل ریڈ ماڈل میں دستیاب نہیں',
      'handoverTitle': 'ورکشاپ QC اور فلیٹ حوالگی',
      'handoverHint': 'ورکشاپ تکمیل اور فلیٹ قبولیت الگ الگ درج ہوتی ہیں۔',
      'slaTitle': 'SLA اور جواب دہ ذمہ دار',
      'slaHint':
          'SLA گھڑیاں سرور کی منتقلیوں سے شروع اور بند ہوتی ہیں، اس اسکرین سے نہیں۔',
      'slaUnavailable':
          'اس ریڈ ماڈل میں SLA مثال، آخری وقت یا توقف کی تاریخ شامل نہیں۔',
      'currentOwner': 'موجودہ ذمہ دار',
      'noActiveOwner': 'فعال ورک اسٹریم کا کوئی ذمہ دار درج نہیں۔',
      'routeCompletion': 'روٹ کی تکمیل',
      'routeCompletionUnavailable': 'روٹ پر مبنی تکمیل درج نہیں۔',
      'timelineTitle': 'ورک اسٹریم تازہ کاریاں',
      'timelineHint': 'ہر ورک اسٹریم کی تازہ ترین تاریخ والی تبدیلی',
      'timelineEmpty': 'کوئی تاریخ والی ورک اسٹریم تازہ کاری درج نہیں۔',
      'notificationsTitle': 'اطلاعات اور ای میل',
      'notificationsHint': 'آپ کے اکاؤنٹ کی کیس سے منسلک اندرونی اطلاعات',
      'notificationsNoWorkspace':
          'سائن اِن سیاق دستیاب نہیں، اس لیے اطلاعات حاصل نہیں کی گئیں۔',
      'notificationsLoading': 'کیس اطلاعات لوڈ ہو رہی ہیں…',
      'notificationsFailed': 'کیس اطلاعات لوڈ نہیں ہو سکیں۔',
      'notificationsEmpty': 'آپ کے ان باکس میں کیس سے منسلک اطلاع نہیں۔',
      'notificationCountOne': 'کیس کی ایک اطلاع',
      'notificationCountMany': 'کیس کی %count% اطلاعات',
      'emailUnavailable':
          'ای میل فعالیت اور ترسیل کی تاریخ سرور کے زیر کنٹرول ہے اور اس ریڈ ماڈل میں شامل نہیں۔',
      'unread': 'نہیں پڑھی',
      'read': 'پڑھی گئی',
      'localPreviewTitle': 'مقامی ورک فلو پیش نظارہ',
      'localPreviewMessage':
          'پیش نظارہ ریکارڈ اور تبدیلیاں صرف اس اسکرین پر رہتی ہیں۔ Tyre Pulse کو کچھ جمع نہیں ہوتا۔',
      'localChange': 'مقامی تبدیلی',
      'responsibilityChoice': 'ذمہ داری کا فیصلہ',
      'payerChoice': 'متوقع ادائیگی کنندہ',
      'liabilityUnderInvestigation': 'زیر تفتیش',
      'liabilityCompanyDriver': 'کمپنی ڈرائیور',
      'liabilityThirdParty': 'تیسرا فریق',
      'liabilityShared': 'مشترکہ ذمہ داری',
      'liabilityOurDriverGcc': 'ہمارا ڈرائیور / GCC',
      'liabilityOtherParty': 'دوسرا فریق',
      'liabilityNotApplicable': 'لاگو نہیں',
      'payerInsurer': 'بیمہ کنندہ',
      'payerCompany': 'کمپنی',
      'payerThirdParty': 'تیسرا فریق',
      'payerOtherPartyInsurance': 'دوسرے فریق کا بیمہ',
      'payerOurInsurance': 'ہمارا بیمہ',
      'payerGccCompany': 'GCC / کمپنی',
      'payerDriverRecovery': 'ڈرائیور وصولی',
      'payerWarranty': 'وارنٹی',
      'payerPending': 'زیر التوا',
      'liabilityPercent': 'ذمہ داری فیصد',
      'provisionalAuditNote': 'عارضی / آڈٹ نوٹ',
      'responsibleCompany': 'ذمہ دار کمپنی',
      'failedParty': 'ناکام / ذمہ دار کمپنی',
      'documentRegister': 'کیس دستاویز رجسٹر',
      'document': 'دستاویز',
      'reference': 'حوالہ',
      'updated': 'تازہ کاری',
      'authorityReport': 'اتھارٹی / پولیس رپورٹ',
      'driverStatement': 'ڈرائیور بیان',
      'insurancePolicy': 'بیمہ پالیسی کی نقل',
      'workshopAssessmentDocument': 'ورکشاپ جائزہ',
      'repairQuotationDocument': 'مرمت کوٹیشن',
      'purchaseOrderDocument': 'خریداری آرڈر',
      'policeReport': 'پولیس رپورٹ',
      'najmReport': 'نجم رپورٹ',
      'taqdeerAssessment': 'تقدیر جائزہ / نمبر',
      'thirdPartyRegistration': 'تیسرے فریق کی گاڑی رجسٹریشن',
      'thirdPartyPolicy': 'تیسرے فریق کی بیمہ پالیسی',
      'drivingLicence': 'ڈرائیونگ لائسنس',
      'companyUndertaking': 'کمپنی حلف نامہ (اختیاری)',
      'vehicleRegistration': 'گاڑی رجسٹریشن',
      'accidentPhotos': 'حادثے کی تصاویر',
      'uploadedBy': 'اپ لوڈ کنندہ',
      'mandatory': 'لازمی',
      'optional': 'اختیاری',
      'statusComplete': 'مکمل',
      'statusInProgress': 'جاری',
      'statusPending': 'زیر التوا',
      'statusWarning': 'توجہ درکار',
      'statusMissing': 'نامکمل',
      'statusVerified': 'تصدیق شدہ',
      'statusDelivered': 'پہنچایا گیا',
      'statusQueued': 'قطار میں',
      'statusScheduled': 'طے شدہ',
      'statusSigned': 'دستخط شدہ',
      'claimPackageTitle': 'دعویٰ پیکج',
      'claimPackageHint':
          'پالیسی، دعویٰ دستاویزات اور بیمہ فیصلہ ایک جواب دہ پیکج میں',
      'claimRecoveryTitle': 'تصفیہ اور وصولی',
      'claimRecoveryHint': 'دعویٰ، منظور، وصول اور باقی رقم الگ رہتی ہیں',
      'insurerDecision': 'بیمہ کنندہ کا فیصلہ',
      'approvedForSettlement': 'تصفیے کے لیے منظور',
      'outstandingRecovery': 'باقی وصولی',
      'previewAmount': 'پیش نظارہ رقم',
      'repairRouteDecision': 'مرمتی راستے کا فیصلہ',
      'internalWorkshop': 'اندرونی ورکشاپ',
      'authorisedDealer': 'مجاز ڈیلر',
      'externalWorkshop': 'بیرونی ورکشاپ',
      'totalLoss': 'مکمل نقصان',
      'onSiteRepair': 'موقع پر مرمت',
      'safeToMove': 'چلانے کے لیے محفوظ',
      'towingRequired': 'ٹو کرنا ضروری',
      'vehicleOffRoad': 'گاڑی آف روڈ',
      'yes': 'ہاں',
      'no': 'نہیں',
      'labourHours': 'تخمینی لیبر گھنٹے',
      'labourCost': 'تخمینی لیبر لاگت',
      'partsAvailability': 'پرزہ دستیابی',
      'partsCount': '%required% میں سے %available% پرزے دستیاب',
      'workshopRecommendation': 'ورکشاپ سفارش',
      'externalRepairFlow': 'بیرونی ورکشاپ حوالگی',
      'externalRepairFlowHint':
          'فلیٹ / ورکشاپ گاڑی بھیجتا ہے۔ آمد کے بعد وینڈر کوٹیشن دیتا ہے، پھر Tyre Pulse موازنہ اور PO درج کرتا ہے اور اس کے بعد مرمت شروع ہوتی ہے۔',
      'vehicleDispatchedMilestone': 'گاڑی ورکشاپ بھیجی گئی',
      'externalWorkshopArrivalMilestone': 'بیرونی ورکشاپ آمد کی تصدیق',
      'vendorQuotationReceivedMilestone': 'وینڈر کوٹیشن موصول',
      'quotationComparedMilestone': 'کوٹیشن کا موازنہ اور انتخاب',
      'purchaseOrderRecordedMilestone': 'خریداری آرڈر درج',
      'repairStartMilestone': 'مرمت شروع ہونے کی تصدیق',
      'fleetWorkshopCoordinator': 'فلیٹ / ورکشاپ کوآرڈینیٹر',
      'externalWorkshopCoordinator': 'بیرونی ورکشاپ کوآرڈینیٹر',
      'handoffAt': 'حوالگی کا وقت',
      'quotationRegister': 'کوٹیشن موازنہ',
      'vendor': 'وینڈر / ذریعہ',
      'amount': 'رقم',
      'turnaround': 'مدت',
      'days': 'دن',
      'selected': 'منتخب',
      'internalWorkshopEstimate': 'اندرونی ورکشاپ تخمینہ',
      'authorisedRepairCentre': 'مجاز مرمتی مرکز',
      'purchaseOrderControl': 'خریداری آرڈر کنٹرول',
      'poReference': 'PO حوالہ',
      'poOwner': 'PO ذمہ دار',
      'recordPoRepairStart': 'پرچیز آرڈر مقامی طور پر درج کریں',
      'startRepairLocally': 'پرچیز آرڈر کے بعد مرمت مقامی طور پر شروع کریں',
      'poRecordedLocal':
          'پرچیز آرڈر اس مقامی پیش نظارے میں درج ہو گیا؛ اب مرمت شروع کی جا سکتی ہے۔',
      'repairStartedLocal': 'مرمت آغاز اس مقامی پیش نظارے میں درج ہو گیا۔',
      'procurementManager': 'پروکیورمنٹ مینیجر',
      'handoverReceipt': 'حوالگی رسید',
      'handoverChecklist': 'فلیٹ قبولیت چیک لسٹ',
      'repairScopeCompleted': 'منظور مرمتی دائرہ مکمل',
      'roadTestCompleted': 'روڈ ٹیسٹ مکمل',
      'warningLightsClear': 'ڈیش بورڈ وارننگ لائٹس صاف',
      'handoverPhotosAttached': 'حوالگی تصاویر منسلک',
      'fleetAcceptance': 'فلیٹ قبولیت درج',
      'workshopSignature': 'ورکشاپ دستخط',
      'fleetSignature': 'فلیٹ انسپکٹر دستخط',
      'pendingSignature': 'دستخط زیر التوا',
      'receiptNumber': 'رسید نمبر',
      'toggleChecklistHint': 'مقامی پیش نظارہ بدلنے کے لیے قطار پر ٹیپ کریں۔',
      'slaRegister': 'SLA ذمہ داری رجسٹر',
      'assignedActors': 'نامزد جوابدہ افراد',
      'activity': 'سرگرمی',
      'target': 'ہدف',
      'owner': 'ذمہ دار',
      'due': 'آخری وقت',
      'fleetValidationActivity': 'فلیٹ تصدیق',
      'insuranceReviewActivity': 'بیمہ جائزہ',
      'repairEstimateActivity': 'ابتدائی مرمت تخمینہ',
      'poAfterApprovalActivity': 'منظوری کے بعد PO',
      'fleetInspectionActivity': 'مرمت کے بعد فلیٹ معائنہ',
      'fourWorkingHours': '4 کام کے گھنٹے',
      'oneBusinessDay': '1 کاروباری دن',
      'twoBusinessDays': '2 کاروباری دن',
      'fleetSupervisor': 'فلیٹ سپروائزر',
      'insuranceClaimsOfficer': 'بیمہ کلیمز افسر',
      'workshopPlanner': 'ورکشاپ پلانر',
      'procurementOfficer': 'پروکیورمنٹ افسر',
      'fleetInspector': 'فلیٹ انسپکٹر',
      'pmvManager': 'PMV مینیجر',
      'fleetIncidentOfficer': 'فلیٹ حادثہ افسر',
      'hseOfficer': 'HSE افسر',
      'incidentSubmittedEvent': 'حادثہ جمع ہوا',
      'fleetValidatedEvent': 'فلیٹ تصدیق مکمل',
      'liabilityReviewEvent': 'ذمہ داری جائزہ کھلا',
      'claimPackageEvent': 'دعویٰ پیکج تیار',
      'workshopAssessmentEvent': 'ورکشاپ جائزہ طے',
      'closureApprovalAction': 'حتمی بندش منظوری',
      'claimCompleteness': 'دعویٰ دستاویز تکمیل گیٹ',
      'documentsVerified':
          '%required% میں سے %verified% ضروری دستاویزات تصدیق شدہ',
      'claimReady': 'دعویٰ پیکج تیار',
      'claimBlocked': 'دعویٰ پیکج رکا ہوا',
      'deductible': 'قابل برداشت رقم',
      'netClaimable': 'خالص دعویٰ',
      'financialClosure': 'مالی بندش کی تصدیق',
      'recoveryEditHint':
          'مالی بندش کے بعد وصولی ذریعہ، حوالہ، تاریخ اور رقم قابل تدوین ہوتے ہیں۔',
      'recoverySource': 'وصولی ذریعہ',
      'recoveryReference': 'وصولی حوالہ',
      'recoveryDate': 'وصولی تاریخ',
      'recoveryAmount': 'وصولی رقم',
      'insuranceSettlement': 'بیمہ تصفیہ',
      'recoveryThirdParty': 'تیسرے فریق سے وصولی',
      'recoveryDriver': 'ڈرائیور سے وصولی',
      'recoveryWarranty': 'وارنٹی',
      'recoveryCompany': 'کمپنی وصولی',
      'deliveryLog': 'اطلاع ترسیل لاگ',
      'recipientGroups': 'وصول کنندہ گروپ',
      'subject': 'موضوع',
      'recipients': 'وصول کنندگان',
      'channel': 'چینل',
      'caseSubmittedSubject': 'کیس جمع - تصدیق درکار',
      'claimActionSubject': 'دعویٰ پیکج - کارروائی درکار',
      'repairApprovalSubject': 'مرمتی راستہ - منظوری درکار',
      'dailyDigestSubject': 'کیس سرگرمی روزانہ خلاصہ',
      'fleetAndHseRecipients': 'فلیٹ سپروائزر + HSE افسر',
      'insuranceRecipients': 'بیمہ کلیمز + بیمہ مینیجر',
      'repairApprovalRecipients': 'فلیٹ مینیجر + ورکشاپ مینیجر',
      'caseMemberRecipients': 'فعال کیس اراکین',
      'inAppAndEmail': 'ان ایپ + ای میل',
      'inApp': 'ان ایپ',
      'emailDigest': 'ای میل خلاصہ',
    },
  };
}
