import { chromium } from 'playwright';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const fixture = JSON.parse(await readFile(new URL('./fixture.json', import.meta.url), 'utf8'));
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.route('**/src/main.jsx*', route => route.fulfill({ contentType: 'application/javascript', body: "import '/audit/meter-workspace/entry.jsx';" }));
await page.route('**/src/contexts/SettingsContext*', route => route.fulfill({ contentType: 'application/javascript', body: "export const useSettings = () => ({activeCountry: 'KSA'}); export const COUNTRIES = ['KSA','UAE','Egypt'];" }));
await page.route('**/src/lib/api/vehicleMeters.js*', route => route.fulfill({ contentType: 'application/javascript', body: `export async function loadVehicleMeters(){return ${JSON.stringify(fixture)}}; export async function saveVehicleMeters(){throw new Error('Read-only visual check: no production submission');}; export async function correctVehicleMeter(){throw new Error('Read-only visual check');}; export async function meterCorrectionHistory(){return []};` }));
await page.goto('http://127.0.0.1:5178/odometer-logs', { waitUntil: 'commit' });
console.log('Preview document loaded');
await page.getByRole('button', { name: 'Save TM651', exact: true }).waitFor({timeout:60000});
console.log('Meter table rendered');
await page.screenshot({ path: fileURLToPath(new URL('./01-desktop.png', import.meta.url)), fullPage: true });
const nextKm = String(Number(fixture.fleet[0].current_km) + 1);
await page.getByLabel('TM651 new km', { exact: true }).fill(nextKm);
await page.getByRole('button', { name: 'Save TM651', exact: true }).click();
await page.getByRole('alert').waitFor();
if (await page.getByLabel('TM651 new km', { exact: true }).inputValue() !== nextKm) throw new Error('Draft lost after failed save');
await page.getByRole('button', { name: 'All readings', exact: true }).click();
await page.getByRole('columnheader', { name: 'Received at', exact: true }).waitFor();
await page.screenshot({ path: fileURLToPath(new URL('./02-history.png', import.meta.url)), fullPage: true });
await page.getByRole('button', { name: 'Latest per vehicle', exact: true }).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({ path: fileURLToPath(new URL('./03-mobile.png', import.meta.url)), fullPage:true });
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
await page.evaluate(() => { document.documentElement.dir='rtl'; document.documentElement.classList.add('dark'); });
await page.screenshot({ path: fileURLToPath(new URL('./04-rtl-dark.png', import.meta.url)), fullPage:true });
console.log(JSON.stringify({ pageErrors: errors, mobileOverflow: overflow, screenshots: 4, readOnly: true }));
await browser.close();
if (errors.length || overflow) process.exitCode = 1;

