// Generated by scripts/sync-driver-workspace-copy.mjs. Edit shared/driver-workspace-copy.json.
const copy: Record<string, string[]> = {
  "Driver workspace": [
    "مساحة عمل السائق",
    "ڈرائیور کا کام"
  ],
  "My fines, team assignments and verified work": [
    "مخالفاتي وتكليفات الفريق والعمل المرتبط بي",
    "میرے جرمانے، ٹیم کی ذمہ داریاں اور تصدیق شدہ کام"
  ],
  "Fines, verified work records, supervisors and vehicle assignments": [
    "المخالفات وسجلات العمل والمشرفون وتخصيص المركبات",
    "جرمانے، تصدیق شدہ کام، نگران اور گاڑیوں کی ذمہ داریاں"
  ],
  "Traffic fines": [
    "المخالفات المرورية",
    "ٹریفک جرمانے"
  ],
  "Add verified driver": [
    "إضافة سائق موثّق",
    "تصدیق شدہ ڈرائیور شامل کریں"
  ],
  "Link login account": [
    "ربط حساب الدخول",
    "لاگ ان اکاؤنٹ منسلک کریں"
  ],
  "Assign team and vehicle": [
    "تعيين الفريق والمركبة",
    "ٹیم اور گاڑی تفویض کریں"
  ],
  "Issue traffic fine": [
    "تسجيل مخالفة مرورية",
    "ٹریفک جرمانہ درج کریں"
  ],
  "Link work record": [
    "ربط سجل عمل",
    "کام کا ریکارڈ منسلک کریں"
  ],
  "Review and sign": [
    "مراجعة وتوقيع",
    "جائزہ لیں اور دستخط کریں"
  ],
  "Review response / payment": [
    "مراجعة الرد أو السداد",
    "جواب یا ادائیگی کا جائزہ"
  ],
  "Acknowledge and respond": [
    "الإقرار بالاستلام والرد",
    "وصولی تسلیم کریں اور جواب دیں"
  ],
  "Review / record payment": [
    "مراجعة أو تسجيل سداد",
    "جائزہ لیں یا ادائیگی درج کریں"
  ],
  "I will pay directly": [
    "سأسدد مباشرة",
    "میں براہ راست ادائیگی کروں گا"
  ],
  "Already paid": [
    "تم السداد بالفعل",
    "پہلے ہی ادا کر دیا ہے"
  ],
  "Dispute / incorrect assignment": [
    "اعتراض أو إسناد غير صحيح",
    "اعتراض یا غلط تفویض"
  ],
  "Request company payment / recovery": [
    "طلب سداد الشركة أو الاسترداد",
    "کمپنی کی ادائیگی یا وصولی کی درخواست"
  ],
  "Request instalments": [
    "طلب التقسيط",
    "قسطوں کی درخواست"
  ],
  "Employee ID": [
    "الرقم الوظيفي",
    "ملازم نمبر"
  ],
  "Driver name": [
    "اسم السائق",
    "ڈرائیور کا نام"
  ],
  "Country": [
    "الدولة",
    "ملک"
  ],
  "Site": [
    "الموقع",
    "مقام"
  ],
  "Supervisor": [
    "المشرف",
    "نگران"
  ],
  "Manager": [
    "المدير",
    "منیجر"
  ],
  "Vehicle": [
    "المركبة",
    "گاڑی"
  ],
  "Login account (none removes link)": [
    "حساب الدخول (بدون يلغي الربط)",
    "لاگ ان اکاؤنٹ (کوئی نہیں سے ربط ختم ہوگا)"
  ],
  "Login account (blank removes link)": [
    "حساب الدخول (تركه فارغاً يلغي الربط)",
    "لاگ ان اکاؤنٹ (خالی سے ربط ختم ہوگا)"
  ],
  "Identity verification / reason": [
    "التحقق من الهوية أو السبب",
    "شناخت کی تصدیق یا وجہ"
  ],
  "Assignment reason": [
    "سبب التكليف",
    "تفویض کی وجہ"
  ],
  "Issuing authority": [
    "الجهة المُصدرة",
    "جاری کرنے والا ادارہ"
  ],
  "Notice reference": [
    "رقم المخالفة",
    "نوٹس کا حوالہ"
  ],
  "Incident date and time": [
    "تاريخ ووقت المخالفة",
    "واقعے کی تاریخ اور وقت"
  ],
  "Incident date and time (YYYY-MM-DDTHH:mm)": [
    "تاريخ ووقت المخالفة (YYYY-MM-DDTHH:mm)",
    "واقعے کی تاریخ اور وقت (YYYY-MM-DDTHH:mm)"
  ],
  "Due date": [
    "تاريخ الاستحقاق",
    "آخری تاریخ"
  ],
  "Due date (YYYY-MM-DD)": [
    "تاريخ الاستحقاق (YYYY-MM-DD)",
    "آخری تاریخ (YYYY-MM-DD)"
  ],
  "Fine amount": [
    "قيمة المخالفة",
    "جرمانے کی رقم"
  ],
  "Currency code": [
    "رمز العملة",
    "کرنسی کوڈ"
  ],
  "Notice details": [
    "تفاصيل المخالفة",
    "نوٹس کی تفصیلات"
  ],
  "Evidence confirming driver assignment": [
    "دليل إسناد المخالفة للسائق",
    "ڈرائیور کی ذمہ داری کی تصدیق کا ثبوت"
  ],
  "Record type": [
    "نوع السجل",
    "ریکارڈ کی قسم"
  ],
  "Existing record": [
    "السجل الموجود",
    "موجودہ ریکارڈ"
  ],
  "How driver identity was verified": [
    "كيفية التحقق من هوية السائق",
    "ڈرائیور کی شناخت کیسے تصدیق کی گئی"
  ],
  "Preferred resolution": [
    "طريقة المعالجة المطلوبة",
    "مطلوبہ حل"
  ],
  "Explanation / proposed arrangement": [
    "التوضيح أو الترتيب المقترح",
    "وضاحت یا مجوزہ انتظام"
  ],
  "Payment reference (if paid)": [
    "مرجع السداد إن تم",
    "ادائیگی کا حوالہ (اگر ادا ہو چکا ہے)"
  ],
  "Proposed payment date": [
    "تاريخ السداد المقترح",
    "مجوزہ ادائیگی کی تاریخ"
  ],
  "Proposed payment date (YYYY-MM-DD)": [
    "تاريخ السداد المقترح (YYYY-MM-DD)",
    "مجوزہ ادائیگی کی تاریخ (YYYY-MM-DD)"
  ],
  "Decision": [
    "القرار",
    "فیصلہ"
  ],
  "Review reason / approved arrangement": [
    "سبب المراجعة أو الترتيب المعتمد",
    "جائزے کی وجہ یا منظور شدہ انتظام"
  ],
  "Verified payment reference": [
    "مرجع السداد المتحقق منه",
    "تصدیق شدہ ادائیگی کا حوالہ"
  ],
  "Verified payment amount": [
    "قيمة السداد المتحقق منها",
    "تصدیق شدہ ادائیگی کی رقم"
  ],
  "approve": [
    "اعتماد الطلب",
    "درخواست منظور کریں"
  ],
  "return": [
    "إعادة للسائق",
    "ڈرائیور کو واپس بھیجیں"
  ],
  "payment": [
    "تسجيل سداد متحقق منه",
    "تصدیق شدہ ادائیگی درج کریں"
  ],
  "cancel": [
    "إلغاء المخالفة",
    "جرمانہ منسوخ کریں"
  ],
  "reopen": [
    "إعادة فتح",
    "دوبارہ کھولیں"
  ],
  "open": [
    "مفتوحة",
    "کھلا"
  ],
  "settled": [
    "مسددة",
    "ادا شدہ"
  ],
  "cancelled": [
    "ملغاة",
    "منسوخ"
  ],
  "awaiting response": [
    "بانتظار الرد",
    "جواب کا انتظار"
  ],
  "submitted": [
    "تم إرسال الرد",
    "جواب جمع ہو گیا"
  ],
  "returned": [
    "أعيدت للسائق",
    "ڈرائیور کو واپس"
  ],
  "approved": [
    "معتمدة",
    "منظور شدہ"
  ],
  "Team and vehicle assignment history": [
    "سجل تكليفات الفريق والمركبة",
    "ٹیم اور گاڑی کی ذمہ داریوں کی تاریخ"
  ],
  "Verified work and driver records": [
    "سجلات العمل والسائق الموثّقة",
    "تصدیق شدہ کام اور ڈرائیور کے ریکارڈ"
  ],
  "Activity history": [
    "سجل النشاط",
    "سرگرمی کی تاریخ"
  ],
  "View signed acknowledgment": [
    "عرض الإقرار الموقّع",
    "دستخط شدہ رسید دیکھیں"
  ],
  "Attach receipt photo": [
    "إرفاق صورة إيصال",
    "رسید کی تصویر منسلک کریں"
  ],
  "Attach supporting photo": [
    "إرفاق صورة داعمة",
    "معاون تصویر منسلک کریں"
  ],
  "Attach official notice photo": [
    "إرفاق صورة المخالفة الرسمية",
    "سرکاری نوٹس کی تصویر منسلک کریں"
  ],
  "Share fine statement PDF": [
    "مشاركة كشف المخالفات PDF",
    "جرمانوں کی PDF تفصیل شیئر کریں"
  ],
  "Export fine statement PDF": [
    "تصدير كشف المخالفات PDF",
    "جرمانوں کی PDF تفصیل نکالیں"
  ],
  "Save draft on this device": [
    "حفظ مسودة على هذا الجهاز",
    "اس آلے پر مسودہ محفوظ کریں"
  ],
  "Draft saved. It has not been submitted.": [
    "تم حفظ المسودة ولم تُرسل بعد.",
    "مسودہ محفوظ ہو گیا۔ ابھی جمع نہیں ہوا۔"
  ],
  "Draw signature": [
    "رسم التوقيع",
    "دستخط بنائیں"
  ],
  "Search drivers": [
    "البحث عن السائقين",
    "ڈرائیور تلاش کریں"
  ],
  "Search": [
    "بحث",
    "تلاش"
  ],
  "Back": [
    "رجوع",
    "واپس"
  ],
  "Back to drivers": [
    "العودة للسائقين",
    "ڈرائیوروں کی فہرست پر واپس"
  ],
  "Refresh": [
    "تحديث",
    "تازہ کریں"
  ],
  "Submit": [
    "إرسال",
    "جمع کریں"
  ],
  "Cancel": [
    "إلغاء",
    "منسوخ"
  ],
  "Saving…": [
    "جارٍ الحفظ…",
    "محفوظ ہو رہا ہے…"
  ],
  "Previous options": [
    "الخيارات السابقة",
    "پچھلے اختیارات"
  ],
  "More options": [
    "مزيد من الخيارات",
    "مزید اختیارات"
  ],
  "None / clear selection": [
    "بدون أو مسح الاختيار",
    "کوئی نہیں یا انتخاب ختم کریں"
  ],
  "No fines recorded.": [
    "لا توجد مخالفات مسجلة.",
    "کوئی جرمانہ درج نہیں ہے۔"
  ],
  "No assignment recorded.": [
    "لا يوجد تكليف مسجل.",
    "کوئی ذمہ داری درج نہیں ہے۔"
  ],
  "Unmatched historical records require identity review before they appear here.": [
    "تتطلب السجلات السابقة غير المرتبطة التحقق من الهوية قبل عرضها هنا.",
    "پرانے غیر منسلک ریکارڈ یہاں ظاہر ہونے سے پہلے شناخت کی تصدیق چاہتے ہیں۔"
  ],
  "No linked driver or assigned team is available. Ask an authorized manager to verify your account and assignment.": [
    "لا يوجد سائق مرتبط أو فريق مكلّف. اطلب من مدير مخوّل التحقق من حسابك وتكليفك.",
    "کوئی منسلک ڈرائیور یا تفویض شدہ ٹیم موجود نہیں۔ مجاز منیجر سے اکاؤنٹ اور ذمہ داری کی تصدیق کروائیں۔"
  ],
  "Offline cached view. Connect and refresh before responding or reviewing.": [
    "عرض محفوظ دون اتصال. اتصل وحدّث قبل الرد أو المراجعة.",
    "آف لائن محفوظ منظر۔ جواب یا جائزے سے پہلے رابطہ بحال کرکے تازہ کریں۔"
  ],
  "Submission requires a connection so the current notice and your access can be checked.": [
    "يتطلب الإرسال اتصالاً للتحقق من آخر نسخة للمخالفة وصلاحياتك.",
    "جمع کرنے کے لیے رابطہ ضروری ہے تاکہ موجودہ نوٹس اور آپ کی اجازت کی جانچ ہو۔"
  ],
  "Approval records the reviewed arrangement. It does not execute payment or payroll deduction. Record only verified payments.": [
    "يسجّل الاعتماد الترتيب الذي تمت مراجعته ولا ينفّذ سداداً أو خصماً من الراتب. سجّل الدفعات المتحقق منها فقط.",
    "منظوری جائزہ شدہ انتظام درج کرتی ہے۔ یہ ادائیگی یا تنخواہ سے کٹوتی نہیں کرتی۔ صرف تصدیق شدہ ادائیگیاں درج کریں۔"
  ],
  "I acknowledge receipt and review of this notice and submit the response shown above. Receipt does not mean admission of responsibility. A payment or recovery request does not authorize an automatic payment or payroll deduction.": [
    "أقر باستلام هذه المخالفة ومراجعتها وأقدم الرد الموضح أعلاه. الاستلام لا يعني الإقرار بالمسؤولية. طلب السداد أو الاسترداد لا يجيز سداداً تلقائياً أو خصماً من الراتب.",
    "میں اس نوٹس کی وصولی اور جائزے کی تصدیق کرتا ہوں اور اوپر دیا گیا جواب جمع کرتا ہوں۔ وصولی ذمہ داری قبول کرنے کا اقرار نہیں ہے۔ ادائیگی یا وصولی کی درخواست خودکار ادائیگی یا تنخواہ کی کٹوتی کی اجازت نہیں دیتی۔"
  ],
  "Position not recorded": [
    "المسمى الوظيفي غير مسجل",
    "عہدہ درج نہیں ہے"
  ]
}
export function driverCopy(value: string, language = 'en'): string { return copy[value]?.[language === 'ar' ? 0 : language === 'ur' ? 1 : -1] || value }
