/// One piece of work assigned to the signed-in person, whatever its source.
///
/// "My tasks", "My work" and "Today's field plan" are three views of the SAME
/// list, so the list is built once, here, and each screen only arranges it.
/// Every field is read from a real source row - a checklist assignment, a
/// checklist draft on this device, an inspection plan, a work order assigned
/// to this person, or a corrective action. Nothing is invented: a field the
/// source does not carry stays null and the screen says so or leaves it out.
///
/// # Time is honest
///
/// `checklist_assignments.due_date` and `inspection_schedules.scheduled_date`
/// are Postgres `date` columns. They carry a DAY, never a time, so [dueDay] is
/// date-only and [dueAt] is set only when the source genuinely carries a time
/// (an inspection plan's `inspection_time`, or a corrective action whose
/// `due_date` timestamp is not midnight). "Overdue by 35 min" is only ever
/// shown for an item with a real [dueAt]; a date-only item is late by DAYS.
library;

import 'package:flutter/foundation.dart';

/// Where a [MyWorkItem] came from. Drives the icon, the action and the route.
enum MyWorkKind {
  /// A `checklist_assignments` row generated by a schedule for this role.
  checklist,

  /// A checklist started on THIS device and not yet submitted, with no open
  /// assignment behind it.
  draft,

  /// An `inspection_schedules` plan assigned to this profile.
  inspectionPlan,

  /// A work order assigned to this person (`wo_assignments` or
  /// `work_orders.assigned_owner_id`).
  workOrder,

  /// A `corrective_actions` row.
  correctiveAction,
}

/// Where an item stands, worst first. The order is the order a crew acts in.
enum MyWorkState { overdue, inProgress, dueToday, upcoming, completed }

@immutable
final class MyWorkItem {
  const MyWorkItem({
    required this.id,
    required this.kind,
    required this.state,
    this.title,
    this.reference,
    this.assetNo,
    this.site,
    this.dueDay,
    this.dueAt,
    this.answered,
    this.total,
    this.priority,
    this.status,
    this.description,
    this.assignedTo,
    this.templateId,
    this.assignmentId,
    this.draftKey,
    this.sourceId,
  });

  /// Stable across refreshes, unique across sources (`kind:sourceId`).
  final String id;
  final MyWorkKind kind;
  final MyWorkState state;

  /// The source's own name for the work. Null when the source row carries
  /// none (a work order row read here has no title column), in which case
  /// the screen shows the kind label instead.
  final String? title;

  /// A second identifier worth showing: the work order number.
  final String? reference;
  final String? assetNo;
  final String? site;

  /// The day the work is due, local, date-only.
  final DateTime? dueDay;

  /// A real due moment, when the source carries a time. See library comment.
  final DateTime? dueAt;

  /// Progress of an on-device checklist draft.
  final int? answered;
  final int? total;

  final String? priority;
  final String? status;
  final String? description;
  final String? assignedTo;

  /// Checklist routing.
  final String? templateId;
  final String? assignmentId;
  final String? draftKey;

  /// The source row id (plan, work order, corrective action).
  final String? sourceId;

  bool get isOpen => state != MyWorkState.completed;

  bool get hasDraft => draftKey != null;

  MyWorkItem copyWith({
    MyWorkState? state,
    int? answered,
    int? total,
    String? draftKey,
  }) =>
      MyWorkItem(
        id: id,
        kind: kind,
        state: state ?? this.state,
        title: title,
        reference: reference,
        assetNo: assetNo,
        site: site,
        dueDay: dueDay,
        dueAt: dueAt,
        answered: answered ?? this.answered,
        total: total ?? this.total,
        priority: priority,
        status: status,
        description: description,
        assignedTo: assignedTo,
        templateId: templateId,
        assignmentId: assignmentId,
        draftKey: draftKey ?? this.draftKey,
        sourceId: sourceId,
      );

  @override
  String toString() => 'MyWorkItem($id, $state)';
}
